# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Raggaerdev"
license = "MIT"
description = ""
homepage = "https://raggaer.dev/"
tags = []
features = []
min_version = "0.41.0"

[module]
  [module.assets]
    fingerprints = true

[author]
  name = "Raggaer"
  homepage = "https://raggaer.dev"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
